version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: veera_postgres2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: employee_db
    ports:
      - "6646:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - veera_net

  backend:
    build: ./Backend
    container_name: veera_backend2
    ports:
      - "3648:3648"
    depends_on:
      - postgres
    volumes:
      - ./Backend/Uploads:/app/Uploads
    environment:
      - NODE_ENV=production
    networks:
      - veera_net

  frontend:
    build: ./Frontend
    container_name: veera_frontend2
    ports:
      - "7616:80"
    depends_on:
      - backend
    networks:
      - veera_net

  hr:
    build: ./HR
    container_name: veera_hr2
    ports:
      - "7617:80"
    depends_on:
      - backend
    networks:
      - veera_net

  staff:
    build: ./Staff
    container_name: veera_staff2
    ports:
      - "7618:80"
    depends_on:
      - backend
    networks:
      - veera_net

volumes:
  pgdata:

networks:
  veera_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.0.0/16

